- name: Get All Packages information in the machine
  ansible.builtin.package_facts:
    manager: auto


- name: Create worker systemd service file
  become: yes
  template:
    src: ./roles/worker/files/worker.service
    dest: /etc/systemd/system/worker.service
  register: conf


- name: Check if worker directory exists
  stat:
    path: ./worker
  register: folder


- name: Extract worker.tar
  become: yes
  unarchive:
    src: ./worker.tar
    dest: ./
  register: file
  when: folder.stat.exists == false


- name: Install dependencies for Worker Host
  become: yes
  apt:
    name: 
      - default-jdk
      - maven


- name: Install dependencies && build the java project
  become: yes
  shell: |
    cd worker mvn dependency:resolve && mvn package
  when: file.changed


- name: Enable worker.service
  become: yes
  ansible.builtin.systemd:
    name: worker
    enabled: yes
    state: started
    daemon_reload: yes
  when: conf.changed


- name: Start worker.service
  become: yes
  ansible.builtin.systemd:
    name: worker
    enabled: yes
    state: started
  when: conf.changed